name: 'Install uv and sccache'
description: 'Install uv and sccache using pip and start sccache server with OBS backend'

inputs:
  hw_obs_ak:
    required: true
    description: 'Huawei OBS Access Key'
  hw_obs_sk:
    required: true
    description: 'Huawei OBS Secret Key'
  sccache_bucket:
    required: false
    default: 'obs-guiiyang1-ascend-test'
    description: 'SCCACHE OBS bucket name'
  sccache_endpoint:
    required: false
    default: 'https://obs.cn-southwest-2.myhuaweicloud.com'
    description: 'SCCACHE OBS endpoint URL'
  sccache_region:
    required: false
    default: 'cn-southwest-2'
    description: 'SCCACHE OBS region'
  sccache_s3_enable_virtual_host_style:
    required: false
    default: 'true'
    description: 'Enable virtual host style for S3'
  sccache_max_frame_length:
    required: false
    default: '104857600'
    description: 'SCCACHE max frame length'
  sccache_idle_timeout:
    required: false
    default: '0'
    description: 'SCCACHE idle timeout'
  sccache_cache_size:
    required: false
    default: '10G'
    description: 'SCCACHE cache size'

runs:
  using: "composite"
  steps:
    - name: Install uv and sccache
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.hw_obs_ak }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.hw_obs_sk }}
        SCCACHE_BUCKET: ${{ inputs.sccache_bucket }}
        SCCACHE_ENDPOINT: ${{ inputs.sccache_endpoint }}
        SCCACHE_REGION: ${{ inputs.sccache_region }}
        SCCACHE_S3_ENABLE_VIRTUAL_HOST_STYLE: ${{ inputs.sccache_s3_enable_virtual_host_style }}
        SCCACHE_MAX_FRAME_LENGTH: ${{ inputs.sccache_max_frame_length }}
        SCCACHE_IDLE_TIMEOUT: ${{ inputs.sccache_idle_timeout }}
        SCCACHE_CACHE_SIZE: ${{ inputs.sccache_cache_size }}
      run: |
        pip install uv
        uv pip install --system sccache
        sccache --start-server
        sccache --show-stats